# Generated by Django 3.2.12 on 2023-03-14 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pics', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('address', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('num_guests', models.IntegerField()),
                ('num_beds', models.IntegerField()),
                ('num_baths', models.IntegerField()),
                ('amenities', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
