# Generated by Django 3.2.12 on 2023-03-15 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymodel',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
