# Generated by Django 4.1.7 on 2023-03-15 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='parent',
            new_name='reply_to',
        ),
    ]
