# Generated by Django 4.1.7 on 2023-03-15 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_comments_address_id_comments_address_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='reply_to',
        ),
    ]
